application: krislion
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /images
  static_dir: images

- url: .*
  script: myproject.wsgi.application

libraries:
- name: django
  version: 1.5
